# Check Lua Formatting
name: Check Lua Formatting

on:
  push:
    branches: ["main"]

jobs:
  stylua-check:
    if: github.repository == 'Doozy134/kickstart.nvim'
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stylua Check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

